language: node_js
node_js:
- '4.0'
- '7.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: npm
    email: tituswormer@gmail.com
    api_key:
      secure: rL1pYkCgpqbRz54BA9pPC8KVKADaNXkruDAxJJGwrysrHqqS3izCer/9VP9XeeEUEWQydZAgHF7GEI7RX8V6rjNjnVXF8ZysBQI3veVeexgSEe67ILfG0XwtCXVC9lTF11yH8Hby94WoZCMHbjOMfjVIzcfvAh7Kqj/wyIzzOk+qfLsx8IMvVPxY3MzvI9Hs5fdDJ1RPYjyMFW3awd7F083KSOVH1HsJek3A7+DwP7D742iFK8oNoq/2DlFbPqZPfoxKcwFerC/onPXuUbPdAaZdz8Fn1LX9yQKblZXSmFKZffIiOvorpp7gji6lv/9X3nB0yV2awNVSV1IGrmvM5JB2M2JYDFEXud6B4laAThPwuVFgHboSgG+Rqm7nXjomTRh7RciXRD96wtPzq7+28ZK18Oh0yFZPsW9d3vBWZwxqdj1Y/5eKybUvyaXgXmIW/ZHmtLBr6WudzFJWNi31LMe5cR5t5gX2xPVZdYmKBfmHajsPC5ZMNBjsuPtsFwMHZCVaaLh9LEv2SkydrRW+bVEQdaoptYESp5BXBZJmn7vktYe8koc4inBES5tJ4MnMEWNw+7xTYom5TY9n0F73usK6u0bWO3yukS+aObK2DAmYmtsdMRlRRUBftudE7muojewFeFkOsHg75jHv7vy9JkNwkFmsJs83ThV+XLOaUBs=
    on:
      tags: true
      node: '4.0'
  - provider: releases
    api_key:
      secure: tDXq0Mkaf+cxtptSbQil2MnQxn44il8ODT0jgxXjbtz9dLHvt7rZW+914KDl3absCt1y5DCdjodBPa6Ds87E5B2+dpiFh/FniYeBSx4OSNPLKtMQkAPMTafmHS/Bs/cDx1MSFjCMnH+BOu/6XJKsyMNfxcoNap0cLyJbUFc+3b9QPB11M8UC8TosUBMXsJlXy4WOp/VHmSJhJgGlicxlDgxCMr737LqrXqtvwVyM+DZqcVTvC7eplDQPZobw+jm3WZaaNGl+ghdzH/vGYhAomT0rGwoiPr8p6awxMvIxUt/DMO6xd56tNMcLbunVvAKyPPxHR8gxFN1Edow22yO/mRxhRKe+2T+fMxh3mSrlLF5ZntBQgPsZCtndCAfAv8al9FvSLqHwqEcNT53sUhvGKCFJUGumAC0OnDLesYge+DDD5HMaWrYtcgZL0Ldqa4dA7jrFPSFTOwPNNMGfWK0USGUKd1q5JtVtZhXLNensLqWzQ1p5GJG1dIxaz05Y3Rvz3S48yJlA0i/v7aE/ipGmxN08lbxmY8HZESPrlUhso60vrvbrx2mrQD8ImQNNq+Ov9f+q5R5855jjMGby7Ga7xXa0sHq38Kbh6RFCzED78Xkk2JCM0BLKPJkaqZWNWr6Qe72v/nZ/a6JDXctvFQaL/aPvIK5Okl4SGk+mAzZO4pU=
    file:
      - "character-entities.js"
      - "character-entities.min.js"
    on:
      tags: true
      node: '7.0'
