language: node_js
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: M1n2TapSCVmqa42zbx1Mzj27vPRugFZM0AS8ewUKEak8in+oP7szvZKVvpXsFOFFlikhZDCXeKvgINvPGJ6VcE//vZQMuJV87/tJBVslynh9CCOMLfkay5pEdZ6/u3ttUKbSpp9q/b6jtcmhly+JDVX/moRBEM6/s1Z9coFgClkv40xLDS3xghM6TtVqkhDoxVYQ6ezDx4+cz2A5gxh+gA5NUU5lDHKjYuh8nBMBMKmNjRPDD5Is+VDRrgTBLNTDuyzDKCvdrcbL1X0DH8gpVfpBRjf84FL0jU6RHNFKuggnDfmYoqDNQyI5OZ8YEe3V94nyp73B82zNhWgGzoVTIKoeARLW403BH5HDQOW+6shVmO3cqsv2ua9f90AblFF2yKu/Lb2IBYlBGhLDRWQlT4B7rFTwOAIpAacBH79NcdL5gFN9BXngxh0skLgzNimNerjAL3x6ZpRWiNx7CtgvzhyI2dTcIfviuYgxd7HfDOqtdWSBMwU6GwGz97rL5VuKv/c/05N9zVADEH5wh5U1bFATWICmfDZFC3jrAuNOcB87R+5b8Qfv04z2Ct6O0ohwq3ieWcQzqBGdOgc37EhjBUS89NLXtqX9pZxYqGq2fQamQuUPsQdShjIj1cS93yA4tuBUCo4foM6iCE+HnZ6yx8IiQNxv+2WG37MI2mjoz0U=
  file:
    - 'character-entities.js'
    - 'character-entities.min.js'
  on:
    tags: true
